# schemachange-config.yml
config-version: 1

root-folder: 2026Q1

vars:
  database_name: DATAMOD
  warehouse_name: VW_DATAMOD_REPORT_S
  schema_name: PUBLIC

change-history-table: DATAMOD.PUBLIC.SCHEMACHANGE_HISTORY
create-change-history-table: true

dry-run: false
autocommit: true
verbose: true
