# schemachange-config.yml
config-version: 1

root-folder: 2026Q1

vars:
  database_name: DATAMOD
  warehouse_name: VW_SHARED_G1_XS
  schema_name: ENT_DEV

change-history-table: DATAMOD.ENT_DEV.SCHEMACHANGE_HISTORY
create-change-history-table: true


dry-run: false
autocommit: true
verbose: true
