-- Environment Setup
USE DATABASE DATAMOD;
USE SCHEMA ENT_<ENV>;

-- DDL
create or replace TABLE LOCATIONS (
	LOCATION_ID NUMBER(38,0),
	LOCATION_NAME VARCHAR(100),
	ADDRESS VARCHAR(200),
	CITY VARCHAR(50),
	COUNTRY VARCHAR(50)
);