-- Environment Setup
USE DATABASE DATAMOD;
USE SCHEMA ENT_<ENV>;

-- DDL
create or replace TABLE ORDERS (
	ORDER_ID NUMBER(38,0),
	CUSTOMER_ID NUMBER(38,0),
	ORDER_DATE DATE,
	TOTAL_AMOUNT NUMBER(12,2),
	STATUS VARCHAR(20)
);