-- Environment Setup
USE DATABASE DATAMOD;
USE SCHEMA ENT_<ENV>;

-- DDL
create or replace TABLE CUSTOMERS (
	CUSTOMER_ID NUMBER(38,0),
	CUSTOMER_NAME VARCHAR(100),
	EMAIL VARCHAR(200),
	PHONE VARCHAR(20),
	CREATED_DATE DATE
);